name: Generate Voiceover

on:
  push:
    paths:
      - "stories/*.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install gTTS
        run: pip install gTTS

      - name: Generate Audio
        run: python scripts/generate_audio.py

      - name: Commit MP3
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add audio/*.mp3
          git commit -m "Added voiceover"
          git push
